# -*- coding: utf-8 -*-
"""reverse_funtion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qxbUCjYxXAw_yQVsEJjOJOVo3rV6RW9Z
"""

List = ["Parth", "Gazal","Sankalp","Priya","Aditya" ]
List.reverse()
print(List)